# Generated by Django 2.2.6 on 2020-02-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0002_sla_actual_difference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GPUserTest',
            new_name='GPUser',
        ),
        migrations.AddField(
            model_name='sla',
            name='user_identifier',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
    ]
