# Generated by Django 2.2.6 on 2020-02-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0003_auto_20200218_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='sla',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
