# Generated by Django 2.2.6 on 2020-02-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0005_auto_20200219_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sla',
            name='expected_difference',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
