# Generated by Django 2.2.6 on 2020-02-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0006_auto_20200219_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sla',
            name='fire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
