# Generated by Django 2.2.6 on 2020-02-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0008_auto_20200219_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='kcp_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
