# Generated by Django 2.2.6 on 2020-02-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0009_auto_20200219_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sla',
            name='actual_difference',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sla',
            name='expected_difference',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
