# Generated by Django 2.2.6 on 2020-02-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0011_auto_20200220_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completed_stages',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
