# Generated by Django 2.2.6 on 2020-02-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0012_ticket_completed_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='completed_stages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
