# Generated by Django 2.2.6 on 2020-02-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0013_auto_20200221_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pending_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
