# Generated by Django 2.2.6 on 2020-02-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0014_auto_20200221_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='kam_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
