# Generated by Django 2.2.6 on 2020-02-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0015_onboarding_kam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='kam_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
