# Generated by Django 2.2.6 on 2020-02-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0016_ticket_kam_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='zone',
            field=models.CharField(blank=True, choices=[('Strategic & Large Accounts', 'Strategic & Large Accounts'), ('Prime Accounts 1', 'Prime Accounts 1'), ('Prime Accounts 2', 'Prime Accounts 2'), ('Prime Accounts 3', 'Prime Accounts 3'), ('Prime Accounts 4', 'Prime Accounts 4'), ('Prime Accounts 5', 'Prime Accounts 5'), ('Govt Accounts', 'Govt Accounts'), ('Large Accounts 1', 'Large Accounts 1'), ('Large Accounts 2', 'Large Accounts 2'), ('Large Accounts 3', 'Large Accounts 3'), ('Emerging Central', 'Emerging Central'), ('Emerging CircleDhaka', 'Emerging CircleDhaka'), ('Emerging CircleGazipur', 'Emerging CircleGazipur'), ('Emerging CircleKhulna', 'Emerging CircleKhulna'), ('Emerging CircleRajshahi', 'Emerging CircleRajshahi'), ('Emerging CircleSylhet', 'Emerging CircleSylhet')], max_length=255, null=True),
        ),
    ]
