# Generated by Django 2.2.6 on 2020-02-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0017_auto_20200224_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='KAMTable',
            fields=[
                ('emp_id', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, choices=[('Prime Account', 'Prime Account'), ('Strategic and Large Account', 'Strategic and Large Account'), ('Emerging Accounts', 'Emerging Accounts'), ('Government Accounts', 'Government Accounts')], max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=11, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('manager', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
