# Generated by Django 2.2.6 on 2020-02-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0018_kamtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='onboarded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kamtable',
            name='department',
            field=models.CharField(blank=True, choices=[('Prime Account', 'Prime Accounts'), ('Strategic and Large Account', 'Strategic and Large Accounts'), ('Emerging Accounts', 'Emerging Accounts'), ('Government Accounts', 'Government Accounts')], max_length=255, null=True),
        ),
    ]
