# Generated by Django 2.2.6 on 2020-02-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0019_auto_20200225_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='btrc_approved_govt_organization',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
