# Generated by Django 2.2.6 on 2020-02-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0020_onboarding_btrc_approved_govt_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='corporate_short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
