# Generated by Django 2.2.6 on 2020-02-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0021_auto_20200225_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('item_type', models.CharField(blank=True, choices=[('PHYSICAL CONN', 'PHYSICAL CONN'), ('DEVICE', 'DEVICE'), ('VIRTUAL CONN', 'VIRTUAL CONN')], max_length=255)),
            ],
        ),
    ]
