# Generated by Django 2.2.6 on 2020-02-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0023_auto_20200225_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='btrc_form_1000',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
