# Generated by Django 2.2.6 on 2020-02-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0024_onboarding_btrc_form_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='bs_customer_region',
            field=models.CharField(blank=True, choices=[('Region 1', 'Region 1'), ('Region 2', 'Region 2'), ('Region 3', 'Region 3')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='cug_id',
            field=models.CharField(blank=True, choices=[('CUG 1', 'CUG 1'), ('CUG 2', 'CUG 2')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='district',
            field=models.CharField(blank=True, choices=[('District 1', 'District 1'), ('District 2', 'District 2')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='thana',
            field=models.CharField(blank=True, choices=[('Thanas 1', 'Thanas 1'), ('Thanas 2', 'Thanas 2')], max_length=255, null=True),
        ),
    ]
