# Generated by Django 2.2.6 on 2020-02-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0025_auto_20200226_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='erp_company_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
