# Generated by Django 2.2.6 on 2020-02-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0026_onboarding_erp_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpuser',
            name='phone_number',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
