# Generated by Django 2.2.6 on 2020-02-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0027_auto_20200227_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
