# Generated by Django 2.2.6 on 2020-03-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0028_onboarding_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrequisition',
            old_name='btrc_form_20191003',
            new_name='previous_btrc_form_20191003',
        ),
        migrations.AddField(
            model_name='productrequisition',
            name='kam_department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productrequisition',
            name='kam_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productrequisition',
            name='previous_btrc_form_20191000',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
