# Generated by Django 2.2.6 on 2020-03-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0029_auto_20200301_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequisition',
            name='sales_credit_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
