# Generated by Django 2.2.6 on 2020-03-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0030_productrequisition_sales_credit_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='zone',
            field=models.CharField(blank=True, choices=[('Emerging Accounts 1', 'Emerging Accounts 1'), ('Government Accounts', 'Government Accounts'), ('Large Account 1', 'Large Account 1'), ('Large Account 2', 'Large Account 2'), ('Large Account 3', 'Large Account 3'), ('Large Account 4', 'Large Account 4'), ('Prime Accounts 1', 'Prime Accounts 1'), ('Prime Accounts 2', 'Prime Accounts 2'), ('Prime Accounts 3', 'Prime Accounts 3'), ('Prime Accounts 4', 'Prime Accounts 4'), ('Prime Accounts Chattogram', 'Prime Accounts Chattogram'), ('SME Circle Chattogram', 'SME Circle Chattogram'), ('SME Circle Dhaka', 'SME Circle Dhaka'), ('SME Circle Gazipur', 'SME Circle Gazipur'), ('SME Circle Khulna', 'SME Circle Khulna'), ('SME Circle Rajshahi', 'SME Circle Rajshahi'), ('SME Circle Sylhet', 'SME Circle Sylhet'), ('Strategic Accounts 1', 'Strategic Accounts 1'), ('Strategic Accounts 2', 'Strategic Accounts 2'), ('Strategic Accounts 3', 'Strategic Accounts 3')], max_length=255, null=True),
        ),
    ]
