# Generated by Django 2.2.6 on 2020-04-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0032_gpuser_pass_change_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpuser',
            name='role',
            field=models.CharField(choices=[('Superadmin', 'Super Admin'), ('KAM', 'KAM'), ('COPC', 'COPC'), ('VA', 'VA'), ('LERP', 'LERP'), ('GERP', 'GERP'), ('CLC', 'CLC'), ('DA', 'DA'), ('Manager', 'Manager')], default='KAM', max_length=10),
        ),
    ]
