# Generated by Django 2.2.6 on 2020-06-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowTool', '0033_auto_20200427_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpuser',
            name='role',
            field=models.CharField(choices=[('Superadmin', 'Super Admin'), ('KAM', 'KAM'), ('COPC', 'COPC'), ('VA', 'VA'), ('LERP', 'LERP'), ('GERP', 'GERP'), ('CLC', 'CLC'), ('DA', 'DA'), ('Manager', 'Manager'), ('Leader', 'Leader')], default='KAM', max_length=10),
        ),
    ]
