# Generated by Django 2.2.6 on 2020-04-06 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fieldops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='data_of_visit',
            new_name='date_of_visit',
        ),
    ]
