# Generated by Django 2.2.6 on 2020-04-06 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fieldops', '0003_visit_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='end_time',
            new_name='end_date',
        ),
    ]
