# Generated by Django 2.2.6 on 2020-04-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldops', '0004_auto_20200406_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_close_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_start_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
