# Generated by Django 2.2.6 on 2020-04-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldops', '0005_auto_20200411_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
