# Generated by Django 2.2.6 on 2020-04-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldops', '0007_visit_visit_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='first_initiated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
