# Generated by Django 2.2.6 on 2020-04-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldops', '0008_auto_20200411_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('purpose', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
