# Generated by Django 2.2.6 on 2020-04-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldops', '0009_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
