# Generated by Django 2.2.6 on 2020-05-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldops', '0010_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='manager',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
